// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhvdajjzfysdqbqrmkae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5odmRhamp6ZnlzZHFicXJta2FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzMzQyNjEsImV4cCI6MjA0OTkxMDI2MX0.t4YqHKkKulYbF7y4-H85jo6y7bGgJAtCOhsy5gf7joE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);